version: '3'
services:
  app:
    build: .
    depends_on:
      - database
    volumes:
      - images:/usr/data
    environment:
      HOST: "0.0.0.0"
    networks:
      - flat-network
  database:
    image: mongo
    volumes:
      - paintings:/data/db
    networks:
      - flat-network
  reverse-proxy:
    build: reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - flat-network

networks:
  flat-network:

volumes:
  images:
    external: true
  paintings:
    external: true
